### ISSUE TITLE
Get rid of status, let main process exit with 1 in case of failure

### ISSUE THREAD

**Issue by fredrikekre** [JuliaRegistries/RegistryCI.jl#107]
It is confusing when you have to go to a :heavy_check_mark: to find the errors.

**Comment by DilumAluthge** [comment]
We need to keep the `automerge/` status. It allows me to programmatically check whether I can merge a PR in a CI-independent way.

But yeah I can make the main process exit with 1 if the automerge guidelines were not met.

**Comment by fredrikekre** [comment]
> We need to keep the automerge/ status. It allows me to programmatically check whether I can merge a PR in a CI-independent way.

Can't we just use the status from the GH Action running the checks for that?

**Comment by DilumAluthge** [comment]
> > We need to keep the automerge/ status. It allows me to programmatically check whether I can merge a PR in a CI-independent way.
> 
> Can't we just use the status from the GH Action running the checks for that?

I'd like to still support Travis.
