### ISSUE TITLE
Rename this package to `RegistryCI.jl` and register it in the General registry?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaRegistries/RegistryCI.jl#11]
It occurs to me that nothing in the `GeneralRegistryCI.jl` package is actually specific to the General registry.

How about we rename this package to something like `RegistryCI.jl` or `RegistryCITools.jl` and register it in the General registry? That way, people that maintain other Julia registries can use this package for automerging in their own registries.

Another benefit of registering this package in the General registry is that the package tests will get run as part of the `NewPkgEval` runs.

**Comment by StefanKarpinski** [comment]
Sure, seems desirable for this to work with any registry, not just General.

**Comment by fredrikekre** [comment]
Yea, I was about to do that the other week, but I guess I got distracted by something.

**Comment by fredrikekre** [comment]
DOne
