### ISSUE TITLE
Always run all checks instead of bailing early

### ISSUE THREAD

**Issue by fredrikekre** [JuliaRegistries/RegistryCI.jl#113]

**Comment by DilumAluthge** [comment]
Yes. Actually I meant to open this issue myself but I forgot.

**Comment by DilumAluthge** [comment]
@fredrikekre This is now deployed on General.

**Comment by DilumAluthge** [comment]
[Here](https://github.com/JuliaRegistries/General/pull/7180#issuecomment-569283731) is an example (from https://github.com/JuliaRegistries/General/pull/7180):

![A8375955-047F-4BBB-93C8-01508F1019EE](https://user-images.githubusercontent.com/5619885/71521969-cdb7d500-2890-11ea-8282-d344543baf83.jpeg)
