### ISSUE TITLE
Automerge should check status of commit to ensure that all checks have been satisfied

### ISSUE THREAD

**Issue by kdheepak** [JuliaRegistries/RegistryCI.jl#123]
Currently AutoMerge might merge a package that has failing tests.

**Comment by fredrikekre** [comment]
IMO it is your (the package authors) responsibility not to release broken packages.

**Comment by kdheepak** [comment]
Sure, but you can say something similar about checking for compat bounds of dependencies and version number increment suggestions, no?

**Comment by DilumAluthge** [comment]
I’m realizing now that this is a duplicate of #120
