### ISSUE TITLE
Should [compat] for stdlibs be required for auto merge?

### ISSUE THREAD

**Issue by tkf** [JuliaRegistries/RegistryCI.jl#19]
Continuing discussion from https://discourse.julialang.org/t/announcement-automatic-merging-for-the-general-registry/29961/12

According to @DilumAluthge, `[compat]` for stdlibs are not required.  But I wonder if it would be a problem if:

> * packages upper-bound `julia` version as `< 2`,
> * stdlibs are decoupled from `julia` distribution, and
> * the packages start lower-bounding stdlib?
>
> In this scenario, IIUC, older packages without stdlib bounds can be chosen by the dependency resolver.  Not that this is the worst problem, since there are so many packages without upper bounds.  But my impression was that start requiring upper bounds was for avoiding this kind of situation and making Julia ecosystem more robust.

**Comment by KristofferC** [comment]
Stdlibs don't currently have versions so I don't see how they could be compat bound (what version would you use, the julia version?). I think we would just need to retroactively upper bound things if a stdlib becomes decoupled and then releases a breaking version.

**Comment by tkf** [comment]
Copying the upper bound of `julia` version to pre-decouple stdlibs sounds good to me.  Maybe even hard-code this in Pkg.jl rather than changing JuliaRegistries/General in-place, since presumably this has to be done in all (possibly private) registries?
