### ISSUE TITLE
Package-specific extra tests

### ISSUE THREAD

**Issue by timholy** [JuliaRegistries/RegistryCI.jl#195]
One feature of the old METADATA was that it ran tests for a random subset of dependent packages. Over at https://github.com/JuliaImages/Images.jl/issues/805, we've wondered about whether it would be possible to add extra tests in a package-specific manner. Perhaps an `ExtraTests.toml` file that would list other packages whose tests should be run using the proposed new version.

It would be extra compute burden for Travis, which is why I ask before thinking about implementation.

**Comment by DilumAluthge** [comment]
I’m moving this issue to RegistryCI.jl since it seems to be a CI feature that would added to this package.

**Comment by DilumAluthge** [comment]
Can I close this as a duplicate of #120?

**Comment by DilumAluthge** [comment]
I'm closing this as a duplicate of #120

**Comment by DilumAluthge** [comment]
Duplicate of #120
