### ISSUE TITLE
Seemingly contradicting and not very helpful error message

### ISSUE THREAD

**Issue by tisztamo** [JuliaRegistries/RegistryCI.jl#259]
github-actions just commented this ([link](https://github.com/JuliaRegistries/General/pull/18180)): 

> Your new version pull request does not meet the following guidelines for auto-merging:
> 
> Does not meet sequential version number guideline: version 0.3.3 skips over 0.3.2
> Note that the guidelines are only required for the pull request to be merged automatically. However, it is strongly recommended to follow them, since otherwise the pull request needs to be manually reviewed and merged by a human.
> 
> **If you want to prevent this pull request from being auto-merged**, simply leave a comment. If you want to post a comment without blocking auto-merging, you must include the text [noblock] in your comment.
> 

Auto-merge is already prevented, isn't?

Also, I felt totally lost when I got this. How can I fix it? After some searching I have found the possible solution here: https://github.com/JuliaRegistries/General#my-pull-request-was-not-approved-for-automatic-merging-what-do-i-do

I think it would be helpful to include this link, or the info it contains.

**Comment by DilumAluthge** [comment]
Yeah there's always room to improve our messages. Pull requests are welcome.

**Comment by DilumAluthge** [comment]
We've now added the following text to the message:

> Please make sure that you have read the [General registry README](https://github.com/JuliaRegistries/General/blob/master/README.md).

So I think this is fixed now.
