### ISSUE TITLE
Julia compat check should consider the same major version

### ISSUE THREAD

**Issue by fredrikekre** [JuliaRegistries/RegistryCI.jl#264]
https://github.com/JuliaRegistries/General/pull/19630#issuecomment-674561423

**Comment by fredrikekre** [comment]
Yes, transferred

**Comment by ericphanson** [comment]
is this the same issue as https://github.com/JuliaRegistries/RegistryCI.jl/issues/180?

**Comment by DilumAluthge** [comment]
I think so.

**Comment by DilumAluthge** [comment]
I'm going to close this as a duplicate of #180.

**Comment by DilumAluthge** [comment]
Duplicate of #180
