### ISSUE TITLE
Restore the "repo URL ends in .jl" AutoMerge check for non-subdirectory packages

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaRegistries/RegistryCI.jl#267]
We should restore this AutoMerge check for packages that are not in a subdirectory.

I'm not 100% sure how this would be implemented in AutoMerge. @fredrikekre any ideas?

**Comment by ericphanson** [comment]
Dup of https://github.com/JuliaRegistries/RegistryCI.jl/issues/244?

**Comment by DilumAluthge** [comment]
Yep.

**Comment by DilumAluthge** [comment]
Any chance you want to take a crack at this? :)

**Comment by ericphanson** [comment]
Not for a few weeks at least, I'm moving to Spain this weekend!

**Comment by DilumAluthge** [comment]
Good luck with the move!
