### ISSUE TITLE
Add approved list of packages that skip installation test

### ISSUE THREAD

**Issue by odow** [JuliaRegistries/RegistryCI.jl#283]
Some packages, particularly in JuMP-dev, have commercial third-party dependencies that we can't provide binaries for. Examples include:
* https://github.com/jump-dev/CPLEX.jl
* https://github.com/jump-dev/Gurobi.jl
* https://github.com/jump-dev/Xpress.jl
* https://github.com/jump-dev/MosekTools.jl

This means such packages can't be `automerge`d because they fail the `Pkg.add` and `import` tests.

To prevent manual merging of every new release, the [proposal here](https://github.com/JuliaRegistries/General/pull/23397#issuecomment-714821893) is to have an approved list of packages somewhere that skip the `Pkg.add` and `import` tests:
https://github.com/JuliaRegistries/RegistryCI.jl/blob/88506ed3a6cae70d593b2eb05be79f97e7ddac63/src/AutoMerge/new-version.jl#L155-L165

Presumably this would be a file in `General` with the name of the package.

**Comment by ericphanson** [comment]
I’m not sure how easy it would be to implement, but I think a good rule could be

- If it’s a new package, always require these tests
- if it’s a new version, and the previous registered version passes these tests, then require them
- if it’s a new version and the previous registered version fails these tests, then skip them 

Then we don’t need a list, and once you get manually merged once you can get auto merged, but if it’s a regression then it needs a manual merge.

**Comment by DilumAluthge** [comment]
Just check if `get(ENV, "JULIA_REGISTRYCI_AUTOMERGE", "") == "true"`. If it is, don't try to load the commercial dependency.

**Comment by DilumAluthge** [comment]
> * if it’s a new version and the previous registered version fails these tests, then skip them

I don't think this is a good idea. The goal of automerge is to be as conservative as possible. We should err on the side of being conservative and requiring manual merge.

**Comment by DilumAluthge** [comment]
The best solution is to make your packages always loadable, even when the commercial dependency is not available.

For example, take a look here: https://github.com/JuliaGPU/CUDA.jl/blob/master/src/initialization.jl

CUDA.jl is always installable and loadable, even if you don't have a GPU.

That's the best solution. An alternative is to check if `get(ENV, "JULIA_REGISTRYCI_AUTOMERGE", "") == "true"`.

@fredrikekre Any thoughts?

**Comment by odow** [comment]
> The best solution is to make your packages always loadable, even when the commercial dependency is not available.

This isn't a good solution for us,  because we have frequent issues of users failing to install the commercial dependency properly. We need to give them an informative error message as early as possible.

> An alternative is to check if `get(ENV, "JULIA_REGISTRYCI_AUTOMERGE", "") == "true"`

This is probably a viable work-around.

**Comment by odow** [comment]
AutoMerge worked: https://github.com/JuliaRegistries/General/pull/23621.

I'm going to close since there is a reasonable work-around. 

For others finding this issue in future, here is how CPLEX.jl does it: https://github.com/jump-dev/CPLEX.jl/pull/335

**Comment by yakir12** [comment]
Dear people, could you please post detailed instructions on how to implement this workaround on Discourse? There are a bunch of these proprietary packages in the ecosystem and if everyone knew how to do this, PRs will come flooding in by users rather than just maintainers: winning. 

Thanks!!!

**Comment by musm** [comment]
How do we add MATLAB.jl to the list? We currently don't have  a way to test it via CI since it is proprietary software. Suggestions are welcome.

**Comment by giordano** [comment]
There is no list: https://github.com/JuliaRegistries/RegistryCI.jl/issues/283#issuecomment-715362834
