### ISSUE TITLE
Disallow `Julia` from package names?

### ISSUE THREAD

**Issue by ericphanson** [JuliaRegistries/RegistryCI.jl#285]
This is one of the guidelines from https://julialang.github.io/Pkg.jl/v1/creating-packages/#Package-naming-guidelines-1 but is not enforced at all. I just saw https://github.com/JuliaRegistries/General/pull/23672 go through (didn't notice the open PR notification only the merge notification) which I don't think is a great name; in this case, I think something like IBMQYao would be much more informative (since it connects IBMQ to Yao.jl).

(For the implementation, my thought for the check would be `!occursin("julia", lowercase(name))` to rule out casing stuff).

**Comment by DilumAluthge** [comment]
Yeah I agree.

Also dup of https://github.com/JuliaRegistries/RegistryCI.jl/issues/112

**Comment by ericphanson** [comment]
Ah whoops, missed that one

**Comment by StefanKarpinski** [comment]
We might want to consider checking for names that start with `Ju` as well. There's been a bunch of those and they inevitably ended up being poor choices. Of course, there's `JuMP`, the exception that proves the rule.
