### ISSUE TITLE
TagBot doesn’t reuse trigger issues in private registries

### ISSUE THREAD

**Issue by ericphanson** [JuliaRegistries/RegistryCI.jl#293]
Since it checks for issues created by @JuliaTagBot when looking to reuse issues.

**Comment by ericphanson** [comment]
Looks like this will be fixed by https://github.com/JuliaRegistries/RegistryCI.jl/pull/292

**Comment by christopher-dG** [comment]
RegistryCI 4.3.5 should do the trick. FYI if you guys are going to use the "fixup" feature where TagBot makes PRs for you, you'll need to give your token the "delete repo" scope which it uses on its own forks.
