### ISSUE TITLE
TODO: Integration tests 

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaRegistries/RegistryCI.jl#31]
Right now, we only have unit tests.

I am planning on writing some integration tests, in which we will make some commits in a test repo, open some pull requests in that test repo, and make sure that everything is working.

**Comment by DilumAluthge** [comment]
This is probably the highest priority issue right now. I'll start working on this as soon as I have some free time.

**Comment by DilumAluthge** [comment]
This is the test repo that I will use for the integration tests: https://github.com/bcbi-test/automerge-integration-test-repo

**Comment by christopher-dG** [comment]
FYI I'm working on a Julia implementation of [vcr](https://github.com/vcr/vcr) which might help with making reproducible HTTP stuff, and [SimpleMock](https://github.com/christopher-dG/SimpleMock.jl) might be useful for mocking Git pushes and such, in case you want to be able to run tests without side effects.

**Comment by DilumAluthge** [comment]
We have integration tests now.
 
We do need to increase our test coverage.
