### ISSUE TITLE
Automerge doesn't catch incorrect `subdir` parameters

### ISSUE THREAD

**Issue by ericphanson** [JuliaRegistries/RegistryCI.jl#349]
hence https://github.com/JuliaRegistries/General/pull/30577. We could check this by `dev`ing the package (instead or in addition to `add`ing it):
```julia
(jl_4zbq4I) pkg> dev YisyAIFramework
     Cloning git-repo `https://github.com/SkyWorld117/YisyAIFramework.jl.git`
   Resolving package versions...
ERROR: expected package `YisyAIFramework [1833fadb]` to exist at path `/Users/eph/.julia/dev/YisyAIFramework/https:/github.com/SkyWorld117/YisyAIFramework.jl`
```
If `dev` doesn't throw, then at least it is a valid directory, though we probably should go one step further and check that the tree hash of the contents at that path matches the one in the registry. If anyone has any other ideas I'd be happy to hear it.

**Comment by DilumAluthge** [comment]
Yeah we should do both `Pkg.add` and `Pkg.dev` to make sure that both work.

**Comment by DilumAluthge** [comment]
> If `dev` doesn't throw, then at least it is a valid directory, though we probably should go one step further and check that the tree hash of the contents at that path matches the one in the registry.

Also agree with this.

**Comment by GunnarFarneback** [comment]
> If dev doesn't throw, then at least it is a valid directory, though we probably should go one step further and check that the tree hash of the contents at that path matches the one in the registry. If anyone has any other ideas I'd be happy to hear it.

It's not quite that easy to go deeper since the registered version wasn't necessarily from the default branch and the latest commit, or there may have been more commits added between the registration and the automerge run. To more properly check that the tree hash is in the right place you need a git clone and do something equivalent to `git rev-list --objects --all | grep <TREE_HASH>` and see that you get the expected subdirectory out of that.

**Comment by GunnarFarneback** [comment]
If Registrator passed on which commit hash it based the registration on it would be much easier to check: `git rev-parse <COMMIT_HASH>:<subdir>`.

**Comment by DilumAluthge** [comment]
> If Registrator passed on which commit hash it based the registration on it would be much easier to check: `git rev-parse <COMMIT_HASH>:<subdir>`.

That should be available in the Registrator PR, right?

**Comment by GunnarFarneback** [comment]
Right, it looks like it is. Then all that's needed is git clone. :-)

**Comment by DilumAluthge** [comment]
Like you said on Slack, that Git clone can be useful for other purposes as well.

**Comment by DilumAluthge** [comment]
I don't think we can do the `Pkg.develop("MyPackageName")` approach, because it will cause AutoMerge to fail in the case where the default branch of a package is not installable. See my comment in https://github.com/JuliaRegistries/RegistryCI.jl/pull/360#issuecomment-797446978

So we'll have to do the "clone the package and check that the tree hash at the subdirectory matches the tree hash in the Registrator PR" approach instead.

**Comment by ericphanson** [comment]
I'm looking at implementing this now. So let's see if I understand.

* Git stores files as "blobs" and directory trees of them as "trees". Trees can be hashed giving the `git-tree-sha`, which corresponds to a set of files in a particular directory configuration. Git commits store the particular tree commit plus parents and a message etc.
* What we probably care about it getting the "Julia package code" which corresponds to a particular git-tree-sha that gets stored in the registry.
* We can get from the git commit to the corresponding tree-sha by `git rev-parse $commit:$subdir` (the colon is important even if the subdir is empty, i.e. top-level in the git repo)
* We can get the files corresponding to a particular tree sha by `git checkout $(tree_hash) .` which will stage them in the repo. (Is there a better way?)

So we could make a temporary directory, clone the package's repo to that directory, get the `git-tree-sha` from the commit (which we already parse out of the registrator message), then run that `git checkout` command to get the corresponding files. Sound right?

**Comment by DilumAluthge** [comment]
> get the `git-tree-sha` from the commit (which we already parse out of the registrator message

I think it's easier than that. We already parse the version number out of the Registrator message. Use `TOML.parsefile` to parse the `Versions.toml` file. The parsed `Versions.toml` file gives you a mapping from version numbers to Git tree SHAs.

**Comment by GunnarFarneback** [comment]
Looks right except for the last point. I don't think you can `git checkout` tree hashes. What can be done instead is `git archive $(tree_hash)`, which will give you a tar archive. Not sure if there's some easier option.

**Comment by ericphanson** [comment]
> I think it's easier than that. We already parse the version number out of the Registrator message. Use TOML.parsefile to parse the Versions.toml file. The parsed Versions.toml file gives you a mapping from version numbers to Git tree SHAs.

Ah great, sounds good.

> Looks right except for the last point. I don't think you can git checkout tree hashes. What can be done instead is git archive $(tree_hash), which will give you a tar archive. Not sure if there's some easier option.

Oddly enough, if you add the `.` at the end it seems you can. I couldn't find it in the documentation but enough googling led me to https://stackoverflow.com/a/17603805, and it seemed to work when I tested it.

**Comment by GunnarFarneback** [comment]
> I think it's easier than that. We already parse the version number out of the Registrator message. Use TOML.parsefile to parse the Versions.toml file. The parsed Versions.toml file gives you a mapping from version numbers to Git tree SHAs.

Depends on whether you just want to get the package itself or if you actually want to solve the problem in this specific issue.

**Comment by DilumAluthge** [comment]
> > I think it's easier than that. We already parse the version number out of the Registrator message. Use TOML.parsefile to parse the Versions.toml file. The parsed Versions.toml file gives you a mapping from version numbers to Git tree SHAs.
> 
> Depends on whether you just want to get the package itself or if you actually want to solve the problem in this specific issue.

I guess we need to do both, right? We need to get the tree hash from the `Versions.toml`, and the tree hash from using the commit, and then compare them to make sure that they are exactly the same. This solves the problem in this issue, right?

Then you can take this tree hash and check it out to get the package code, which we need for the license detection.

**Comment by ericphanson** [comment]
Ok, I think I'll add a "we can get the code" check which will also verify the Versions.toml matches the commit and will fail if there's a mismatch e.g. cloning fails. That will download the code to some prechosen tempdir, just like we are currently doing by making a tempdir to put a depot in. Then later checks like the license check can use the code from that tempdir.

**Comment by GunnarFarneback** [comment]
> I guess we need to do both, right? We need to get the tree hash from the Versions.toml, and the tree hash from using the commit, and then compare them to make sure that they are exactly the same. This solves the problem in this issue, right?

Yes.

**Comment by GunnarFarneback** [comment]
> Oddly enough, if you add the . at the end it seems you can. I couldn't find it in the documentation but enough googling led me to https://stackoverflow.com/a/17603805, and it seemed to work when I tested it.

As far as I can tell this makes a mess of the files if the tree hash is from a subdir.

**Comment by ericphanson** [comment]
> As far as I can tell this makes a mess of the files if the tree hash is from a subdir.

Ok, then I will use archive. Thanks for looking into it!

**Comment by DilumAluthge** [comment]
BTW, instead of using the system `tar`, might be better to use `Tar.jl`.
