### ISSUE TITLE
Error in `read_only` mode on master: `LoadError: type Nothing has no field captures`

### ISSUE THREAD

**Issue by ericphanson** [JuliaRegistries/RegistryCI.jl#384]
https://github.com/JuliaRegistries/General/pull/35596/checks?check_run_id=2460906220#step:13:136

from https://github.com/JuliaRegistries/General/pull/35596

**Comment by DilumAluthge** [comment]
It's not just JLL packages. https://github.com/JuliaRegistries/General/pull/35597

**Comment by DilumAluthge** [comment]
@ericphanson This reminds me: we should document the regexes that we require the PR title and PR body to match. That way, people using AutoMerge in private registries can make sure that their PRs match all of the required regexes.

**Comment by ericphanson** [comment]
Somehow we aren't able to get the body of the PR in question in order to get it's commit hash. In other words https://github.com/JuliaRegistries/RegistryCI.jl/blob/d2d37beb9784a83183536814d610cecaba9f5027/src/AutoMerge/guidelines.jl#L423 is failing. My first thought it somehow our read-only token isn't getting enough permissions to access the body like thaet. The tricky thing is that that's new code on master, so it could also just be broken. However, that code is tested in the integration tests, so it makes me think it's a permissions issue.

**Comment by ericphanson** [comment]
I think we should setup a read-only PAT for RegistryCI's tests like we discussed in #383, because we want that anyway for tests, and it would help us diagnose the issue here.

**Comment by DilumAluthge** [comment]
Easy enough to debug. In `commit_from_pull_request_body`, put an `@info "" body` before the `match`, and we can see if the PR body is being retrieved.

You shouldn't need write access to retrieve the PR body.

**Comment by DilumAluthge** [comment]
I'll generate a read-only PAT for the bot user and upload it as a secret. What do you want me to name the secret?

**Comment by ericphanson** [comment]
maybe `INTEGRATION_TEST_READ_ONLY_TOKEN`?

**Comment by DilumAluthge** [comment]
Wait, actually I think I don't need to do a PAT. I can figure out how to use a read-only GitHub token the same way we do on staging. Let me try it out, and I'll try to make a PR.
