### ISSUE TITLE
Should AutoMerge start requiring upper-bounded `[compat]` entries for JLL dependencies?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaRegistries/RegistryCI.jl#394]
In the ecosystem, we are starting to see cases in which it would have been nice if packages had upper-bounded `[compat]` entries for JLL dependencies. For example: https://github.com/JuliaPackaging/Yggdrasil/pull/2957

Currently, AutoMerge only requires upper-bounded `[compat]` entries for non-JLL dependencies. But I am thinking that maybe we should drop the "non-JLL" part of that, and just require upper-bounded `[compat]` entries for all direct dependencies. What do people think?

**Comment by giordano** [comment]
The fact is jll packages following upstream versions don't follow semver, so IMHO it isn't necessarily a good idea to _require_ the bounds because
1. they don't necessarily make (semver) sense (bzip2 1.0.8 is incompatible with 1.0.6)
2. we can't possibly know in advance what the bounds are

**Comment by DilumAluthge** [comment]
Yeah, I guess for this to really work, we would need to stop versioning JLL packages by the upstream version, and start versioning JLL packages with their own SemVer-compliant version schemes, which is an idea that we have considered and debated during previous Pkg calls.

**Comment by odow** [comment]
> bzip2 1.0.8 is incompatible with 1.0.6

Because of this, I'd suggest list of `=` compatible versions only. Anything else just gets very confusing. 

It's what I did for Ipopt, as an example:
 - [Ipopt.jl](https://github.com/jump-dev/Ipopt.jl/blob/ed23b493a3ee33359d9ccd537a97530cdfca5848/Project.toml#L16)
 - [Ipopt_jll.jl](https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/blob/0136a95909408cb71441f562438c9d0c3040a3a7/Project.toml#L18)

> start versioning JLL packages with their own SemVer-compliant version schemes, which is an idea that we have considered and debated during previous Pkg calls.

:+1: The ["multiply by 100"](https://github.com/JuliaPackaging/Yggdrasil/blob/d16427dd5688f83248e8833ba6ba9689dd71a301/C/Coin-OR/coin-or-common.jl#L3-L28) trick works, but it isn't very nice.

**Comment by giordano** [comment]
Point 2 always stand: we can't possibly know in advance in general when a new version is breaking. Binary libraries can break in uncountable ways, many out of automatic control. So how do you decide when to tag a breaking version? You can't

**Comment by giordano** [comment]
> I'd suggest list of = compatible versions only.

The problem of this approach is that you can _very_ quickly end up with incompatible versions in an environment, especially for packages with many dependents and frequent updates

**Comment by odow** [comment]
> we can't possibly know in advance in general when a new version is breaking

> you can very quickly end up with incompatible versions in an environment

I guess this is the tension. 

For JLLs with few, infrequently changed dependencies it seems okay to have `=`. And I guess if you have more dependencies with frequent updates, hopefully they follow SerVer and you can use looser bounds?

**Comment by giordano** [comment]
> I guess this is the tension

Yes

> hopefully they follow SerVer and you can use looser bounds?

You're incredibly optimistic 🙂 following semver is the exception, rather than the norm. Semver is simply not a thing in the Fortran/C/C++ world, versions are tagged in a rather arbitrary way. The soversion of a library is the thing that in principle should indicate compatibility, but not all packages set it consistently.

**Comment by giordano** [comment]
The bzip2 case is interesting: the only non-JLL package depending on it, CodecBzip2, is not going to have problems with 1.0.8, because the API is the same, what changed is the ABI of the macOS library. Semver applies to the API, not the ABI

**Comment by DilumAluthge** [comment]
I guess maybe I should broaden the question. What can be done to prevent a breakage in a JLL package from breaking large parts of the Julia package ecosystem?

In the example of https://github.com/JuliaRegistries/General/pull/36391, the PR passed all of the AutoMerge checks, and was scheduled to be auto-merged in the next round. The only reason that it wasn't auto-merged was that @giordano manually blocked it. But if it hadn't been manually blocked, it would have been auto-merged.

There are [606 packages](https://juliahub.com/ui/Packages/Bzip2_jll/biC9V/1.0.6+5?t=2) that directly or indirectly depend on Bzip2_jll.jl. If https://github.com/JuliaRegistries/General/pull/36391 had been auto-merged, I am assuming that some (not necessarily proper) subset of those packages would have broken, right?

So, are there any steps that we can take (from the perspective of the General registry) to prevent a broken JLL registration PR from breaking other packages?

**Comment by giordano** [comment]
> I guess maybe I should broaden the question. What can be done to prevent a breakage in a JLL package from breaking large parts of the Julia package ecosystem?

You mean besides running the tests of _all_ downstream packages on _all_ platforms? Nothing.

**Comment by ericphanson** [comment]
Well, if they all would’ve broken on MacOS that suggests we don’t need to test all downstream packages, just one package on all platforms, to stop the biggest issues.

But if our plan is to just not merge if there is breakage, then we don’t need semver or compat I guess? Since we’re just saying we will only have non-breaking version bumps for JLLs. And I guess cut a new JLL for breaking changes (I think there’s already some like this, right?)

**Comment by giordano** [comment]
> Well, if they all would’ve broken on MacOS that suggests we don’t need to test all downstream packages, just one package on all platforms, to stop the biggest issues.

In this case yes, but what if a binary library breaks the API of a single function used by a single package?  This isn't theoretical, this literally happened to me: [`Cuba`](http://www.feynarts.de/cuba/), used by [`Cuba.jl`](https://github.com/giordano/Cuba.jl), in v4.2.1 changed the signature of a function in a backward-incompatible way, compared to v4.2.0 (with a patch release, not even a minor release), forcing me to retroactively fix the compatibility cap of `Cuba`: https://github.com/JuliaRegistries/General/pull/28882.  Mind, `Cuba.jl` _does_ have a compat bound with `Cuba_jll`, but in that case it was totally useless to prevent a breakage: binary packages can and do break things in a completely arbitrary way, with complete disregard for any notion of semantic versioning.  _Requiring_ compat bounds doesn't necessarily save you.

**Comment by DilumAluthge** [comment]
> > I guess maybe I should broaden the question. What can be done to prevent a breakage in a JLL package from breaking large parts of the Julia package ecosystem?
> 
> You mean besides running the tests of _all_ downstream packages on _all_ platforms? Nothing.

One day, we may actually do this. See e.g. the most recent comments in https://github.com/JuliaRegistries/RegistryCI.jl/issues/120.

But it sounds like apart from doing https://github.com/JuliaRegistries/RegistryCI.jl/issues/120, there is nothing we can do to prospectively prevent JLL packages from breaking the ecosystem. It sounds like fixing stuff retroactively (e.g. adding `[compat]` bounds retroactively) is the best we can do.
