### ISSUE TITLE
More informative zeptodoctor report for failed auto-merge

### ISSUE THREAD

**Issue by ablaom** [JuliaRegistries/RegistryCI.jl#40]
If a PR onto General.jl fails to satisfy auto-merge criterion the report generated by zeptodoctor could explain that a new attempt is allowed/recommended?

**Comment by matthieugomez** [comment]
When I updated mine with upper bounds (through JuliaRegistrator), it did not correctly modify the Compat  for some reason --- I had to reopen a new one after asking someone to close it.
https://github.com/JuliaRegistries/General/pull/4575

**Comment by DilumAluthge** [comment]
@matthieugomez That is a separate issue from what is being discussed here. I have opened a new issue: https://github.com/JuliaRegistries/RegistryCI.jl/issues/47

**Comment by caseykneale** [comment]
If a package fails the automerge does it no longer get manually merged? I thought after 3 days packages automatically got merged in but that's not the case for my latest attempt.

**Comment by DilumAluthge** [comment]
@caseykneale That is a slightly different question from the issue being discussed here. I’ve opened a new issue for you: https://github.com/JuliaRegistries/RegistryCI.jl/issues/48

**Comment by DilumAluthge** [comment]
This should be fixed now.

E.g.: 

> Note that the guidelines are only required for the pull request to be merged automatically. However, it is strongly recommended to follow them, since otherwise the pull request needs to be manually reviewed and merged by a human.
> 
> After you have fixed the AutoMerge issues, simple retrigger Registrator, which will automatically update this pull request. You do not need to change the version number in your Project.toml file (unless of course the AutoMerge issue is that you skipped a version number, in which case you should change the version number).
> 
> If you do not want to fix the AutoMerge issues, please post a comment explaining why you would like this pull request to be manually merged.
