### ISSUE TITLE
"mandatory waiting period" value is hardcoded

### ISSUE THREAD

**Issue by ericphanson** [JuliaRegistries/RegistryCI.jl#413]
> Your new package pull request met all of the guidelines for auto-merging and is scheduled to be merged when the mandatory waiting period (3 days) has elapsed.

This isn't always true, the value should be pulled from the argument to `run`.

**Comment by DilumAluthge** [comment]
Yeah that value is actually hardcoded in multiple different places, both in the RegistryCI source code but also in the General registry docs. Hopefully we can fix this as part of #412.
