### ISSUE TITLE
Relax constraint to have proper increments

### ISSUE THREAD

**Issue by tlienart** [JuliaRegistries/RegistryCI.jl#431]
This might seem silly but I very often tag patch releases (e.g. `0.3.7`) and forget to release them and end up tagging the next patch (e.g. `0.3.8`), releasing that, and getting blocked because it skipped over a version. It's a dumb error and leads to an open PR that doesn't meet the guidelines. To close this one has to either

* release the previous proper increment
* re-release the "incorrect" increment

(this has the advantage that it does not require a maintainer closing the blocked PR but it's a bit of faff on my side)

or

* release the previous proper increment
* ask someone to close the blocked PR

Since I'm guilty of doing the latter quite a few times, I now do the former. But it would be far easier if the consistency check just checked that the new version is after the old one and not immediately after (I don't think semver requires this btw?)

Note: xref to a previous request of mine to be able to close failed PR https://github.com/JuliaRegistries/Registrator.jl/issues/296

**Comment by DilumAluthge** [comment]
Hmmm. It seems like the check is working correctly, right? If you tagged 0.3.7, presumably you wanted to register it in the registry, right? So the check is correctly catching mistakes?

**Comment by DilumAluthge** [comment]
> * ask someone to close the blocked PR

For what it's worth, you don't actually need a human to close the blocked PR. All you need to do is:
1. Make a comment on the PR saying "block - please do not merge this" or whatever. As long as your comment does not include the text `noblock`, this will block AutoMerge indefinitely.
2. Just wait for StaleBot to close your PR when it gets stale.

**Comment by tlienart** [comment]
Ah I didn't know about stalebot!

The point of my message was to ask whether it'd be possible to accept tagging 0.3.6 then 0.3.8 even if 0.3.7 hasn't been tagged

It's not really a mistake (no one cares as far as I know that versions are not consecutive) but maybe it's just me 😅

Feel free to close, thanks!
