### ISSUE TITLE
Add a check for case dependent file distinction

### ISSUE THREAD

**Issue by laborg** [JuliaRegistries/RegistryCI.jl#441]
Previously issues against Pkg.jl: Having filenames which only differ by case leads to problems on case insensitive OSes. A check for this would improve user experience.

Previous PR: https://github.com/JuliaLang/Pkg.jl/pull/1099

**Comment by ericphanson** [comment]
We already require packages’ names are not too similar to each other (and in particular disallow only differing by case). Is this issue about something else, or is it already handled by our existing checks?

**Comment by ericphanson** [comment]
Ah, is it to inspect the package code and ensure filepaths within the package are distinct beyond casing? That’s a good idea, and we already clone the repo for the license check.

**Comment by laborg** [comment]
Yes, this is not for checking the package name but to ensure that people developing on e.g. Linux (usually with a case sensitive file system) don't use case in source file names that would lead to problems on e.g. Windows. (happend to me...)

**Comment by GunnarFarneback** [comment]
There are some other things that cause problems on Windows such as filenames with invalid path characters or ending in a dot. The answers to https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names list some things worth checking. [Example found in the wild](https://github.com/bovine3dom/Nauty.jl/blob/master/deps/nauty26r7/This_is_nauty26r7.) (not a registered package).
