### ISSUE TITLE
Remove guideline that patch does not bump Julia compat

### ISSUE THREAD

**Issue by ericphanson** [JuliaRegistries/RegistryCI.jl#455]
I think it's fairly rare that a package actually intends to support older versions of Julia with backports, and we shouldn't *require* the minor version (which means a breaking release for pre-1.0 packages) for automerge.

**Comment by DilumAluthge** [comment]
> (which means a breaking release for pre-1.0 packages)

Note that this check is not enforced for pre-1.0 packages.

**Comment by DilumAluthge** [comment]
https://github.com/JuliaRegistries/RegistryCI.jl/blob/05d18eace0b944591e2cac5090cbda1b49cb1efd/src/AutoMerge/guidelines.jl#L180

**Comment by ericphanson** [comment]
Ohh, I missed that, thanks

**Comment by DilumAluthge** [comment]
Should we document that more prominently somewhere?
