### ISSUE TITLE
Re-commenting on the original commit does not correctly re-trigger Registrator

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaRegistries/RegistryCI.jl#47]
_Originally posted by @matthieugomez in https://github.com/JuliaRegistries/RegistryCI.jl/issues/40#issuecomment-545223025_

> When I updated mine with upper bounds (through JuliaRegistrator), it did not correctly modify the Compat  for some reason --- I had to reopen a new one after asking someone to close it.
https://github.com/JuliaRegistries/General/pull/4575

**Comment by DilumAluthge** [comment]
@matthieugomez I have figured out what happened here.

It looks like you initially triggered Registrator on this commit ("commit 1"): https://github.com/matthieugomez/FixedEffects.jl/commit/2c3af1edc3dec41185f609a736610d3f6e5e7ec2

After automerge gave you suggestions on adding upper-bounded compat bounds, you added those compat bounds on this commit ("commit 2"): https://github.com/matthieugomez/FixedEffects.jl/commit/54b161872efa6111e3593fc6c3d77f884910324c

But then, you re-triggered Registrator by posting another comment on the original commit ("commit 1"). That is why Registrator didn't see the changes you made.

If you make changes, and you want Registrator to update the PR, you need to re-trigger Registrator by posting a comment on the **new commit** ("commit 2").

**Comment by matthieugomez** [comment]
I was under the impression that re-triggering juliaregistrator on a commit would also include all of the commits done since then. Ok sorry for the noise.

**Comment by DilumAluthge** [comment]
No need to apologize! I think we should probably document this better.
