### ISSUE TITLE
LoadError: "/home/runner/work/General/General/I/InstanceOfSingletonType/Deps.toml": No such file

### ISSUE THREAD

**Issue by nsajko** [JuliaRegistries/RegistryCI.jl#494]
https://github.com/JuliaRegistries/General/actions/runs/4028452961/jobs/6925352444#step:16:69

I guess this is caused by the fact that my package has no dependencies?

**Comment by Wikunia** [comment]
Same issue: https://github.com/JuliaRegistries/General/pull/76622

**Comment by byhill** [comment]
Can mine be manually merged too?  https://github.com/JuliaRegistries/General/pull/78310
