### ISSUE TITLE
TODO: Transition to using GitHub Actions completely (instead of Travis)

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaRegistries/RegistryCI.jl#5]

**Comment by DilumAluthge** [comment]
Is GitHub Actions enabled on General? I don’t see the “Actions” tab when I go to https://github.com/JuliaRegistries/General

**Comment by StefanKarpinski** [comment]
Any idea what tab I would look at to enable actions? I looked everywhere I could think of but between webhooks, integrations, third party apps and actions, I have no clue where this setting might be.

**Comment by DilumAluthge** [comment]
You could try this link: https://github.com/features/actions/signup/?account=JuliaRegistries

**Comment by DilumAluthge** [comment]
And then, go here: https://github.com/organizations/JuliaRegistries/settings/member_privileges

And scroll down to the Actions section, and enable it there.

**Comment by DilumAluthge** [comment]
Oh, and then finally, go here: https://github.com/JuliaRegistries/General/settings/actions

And also enable it there

**Comment by StefanKarpinski** [comment]
Ok, should be allowed now. Thta was a crazy process. It's like they don't want anyone to use this.

**Comment by fredrikekre** [comment]
Its still in beta.

**Comment by rapus95** [comment]
Though I think it is good to use the supported framework (Github Actions) here, I want to ask whether the Travis setup will be moved to another repo or if its worth to be maintained somewhere else as for the current future plans about package management and registries the support for external registries is celebrated and thus the need to automate it somewhere else (not on Github) aswell might come up.

**Comment by DilumAluthge** [comment]
I’m not sure how Travis helps you with registries not hosted on GitHub. As far as I am aware, Travis only works with GitHub.
