### ISSUE TITLE
TODO: for new version PR’s, check that the version doesn’t already exist

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaRegistries/RegistryCI.jl#51]
For new versions of existing packages, we should check that the version doesn’t already exist.

Registrator already does this check, but there’s no reason we can’t double check.

**Comment by ericphanson** [comment]
If I’m not mistaken, I think https://github.com/JuliaRegistries/RegistryCI.jl/pull/166 covers this case

**Comment by DilumAluthge** [comment]
I think you’re right, but I’m going to add one last tweak.
