### ISSUE TITLE
AutoMerge fails after successful tests

### ISSUE THREAD

**Issue by andreasvarga** [JuliaRegistries/RegistryCI.jl#529]
I am trying to register a new version of the [PeriodicSystems](https://github.com/andreasvarga/PeriodicSystems.jl). Although the tests for AutoMerge are apparently successful (see [here](https://github.com/JuliaRegistries/General/pull/94412)), the AutoMerge Action fails (see [here](https://github.com/JuliaRegistries/General/actions/runs/6694900176/job/18189247324?pr=94412) for the full error and below for the first few lines of the error message)

```
[2340] signal (2): Interrupt
in expression starting at /home/runner/work/_temp/113ce20a-7fff-4f3d-87e8-ebf400e5055d:4
epoll_wait at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
uv__io_poll at /workspace/srcdir/libuv/src/unix/epoll.c:236
uv_run at /workspace/srcdir/libuv/src/unix/core.c:400
ijl_task_get_next at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/partr.c:390
poptask at ./task.jl:974
wait at ./task.jl:983
#wait#621 at ./condition.jl:130
wait at ./condition.jl:125 [inlined]
wait at ./process.jl:661
success at ./process.jl:523
jfptr_success_27121.clone_1 at /opt/hostedtoolcache/julia/1.9.3/x64/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2940
success at ./process.jl:536
#_run_pkg_commands#148 at /home/runner/.julia/packages/RegistryCI/MNA6P/src/AutoMerge/guidelines.jl:936
_run_pkg_commands at /home/runner/.julia/packages/RegistryCI/MNA6P/src/AutoMerge/guidelines.jl:866 [inlined]
#meets_version_can_be_imported#147 at /home/runner/.julia/packages/RegistryCI/MNA6P/src/AutoMerge/guidelines.jl:843
meets_version_can_be_imported at /home/runner/.julia/packages/RegistryCI/MNA6P/src/AutoMerge/guidelines.jl:811 [inlined]
#145 at /home/runner/.julia/packages/RegistryCI/MNA6P/src/AutoMerge/guidelines.jl:802
unknown function (ip: 0x7f275192a9d6)
```

I would appreciate your guidance how to overcome this error.

**Comment by ericphanson** [comment]
The stacktrace here is somewhat confusing, but I think it is just showing whatever Julia was doing when it hit a 60-minute timeout:
<img width="1070" alt="Screenshot 2023-11-01 at 12 20 17" src="https://github.com/JuliaRegistries/RegistryCI.jl/assets/5846501/3844098e-f54a-4331-a08f-2f9a92899f0f">
<img width="1410" alt="Screenshot 2023-11-01 at 12 20 13" src="https://github.com/JuliaRegistries/RegistryCI.jl/assets/5846501/1ce8ae31-a70c-4295-8308-34063751725e">

Is it expected that it could take 60 minutes to load the package? I know there were some slow network issues, I wonder if that was a factor. I will close and reopen the PR to see if AutoMerge can get it done in time this time.

**Comment by andreasvarga** [comment]
Thanks.
