### ISSUE TITLE
AutoMerge comment could be better organized

### ISSUE THREAD

**Issue by ericphanson** [JuliaRegistries/RegistryCI.jl#544]
Right now it tends to read as a bit of a wall-of-text. I think maybe we could use headings and other formatting bits to try to break it up a bit more.

I think we should also group boilerplate text that appears on all responses (or all failing responses) separately from specific issues it has. We tend to generate it by adding sentences or paragraphs to it, but I think maybe they should be separate sections.

Here I'll include an arbitrarily chosen message, then try to reformat.

# Existing message

Your `new package` pull request does not meet the guidelines for auto-merging. Please make sure that you have read the [General registry README](https://github.com/JuliaRegistries/General/blob/master/README.md) and the [AutoMerge guidelines](https://juliaregistries.github.io/RegistryCI.jl/stable/guidelines/). The following guidelines were not met:

- There is no compat entry for `julia`.
- The following dependencies do not have a `[compat]` entry that is upper-bounded and only includes a finite number of breaking releases: DiffEqCallbacks, FMICore, FMIImport, Requires, SciMLBase

Note that the guidelines are only required for the pull request to be merged automatically. However, it is **strongly recommended** to follow them, since otherwise the pull request needs to be manually reviewed and merged by a human.

After you have fixed the AutoMerge issues, simple retrigger Registrator, which will automatically update this pull request. You do not need to change the version number in your `Project.toml` file (unless of course the AutoMerge issue is that you skipped a version number, in which case you should change the version number).

If you do not want to fix the AutoMerge issues, please post a comment explaining why you would like this pull request to be manually merged. Then, send a message to the `#pkg-registration` channel in the [Julia Slack](https://julialang.org/slack/) to ask for help. Include a link to this pull request.

Since you are registering a new package, please make sure that you have also read the package naming guidelines: https://julialang.github.io/Pkg.jl/dev/creating-packages/#Package-naming-guidelines-1

---
If you want to prevent this pull request from being auto-merged, simply leave a comment. If you want to post a comment without blocking auto-merging, you must include the text `[noblock]` in your comment. You can edit blocking comments, adding `[noblock]` to them in order to unblock auto-merging.

# Reformatting / tweaking of that message

Hello, I am an automated registration bot. I help manage the registration process by checking your registration against a set of [AutoMerge guidelines](https://juliaregistries.github.io/RegistryCI.jl/stable/guidelines/). Meeting these guidelines is only required for the pull request to be **merged automatically**. However, it is **strongly recommended** to follow them, since otherwise the pull request needs to be manually reviewed and merged by a human.

## New package registration

Since you are registering a new package, please make sure that you have read the [package naming guidelines](https://julialang.github.io/Pkg.jl/dev/creating-packages/#Package-naming-guidelines-1).

## [AutoMerge Guidelines](https://juliaregistries.github.io/RegistryCI.jl/stable/guidelines/) which are not met

- There is no compat entry for `julia`.
- The following dependencies do not have a `[compat]` entry that is upper-bounded and only includes a finite number of breaking releases: DiffEqCallbacks, FMICore, FMIImport, Requires, SciMLBase

## What to do next

1. Please try to update your package to conform to these guidelines. The [General registry's README](https://github.com/JuliaRegistries/General/blob/master/README.md) has an FAQ that can help figure out how to do so. You can also leave a comment on this PR (and include `[noblock]`), or send a message to the `#pkg-registration` channel in the [public Julia Slack](https://julialang.org/slack/) to ask for help. Include a link to this pull request if you do so!
2. After you have fixed the AutoMerge issues, simple retrigger Registrator, the same way you did in the initial registration. This will automatically update this pull request. You do not need to change the version number in your `Project.toml` file (unless of course the AutoMerge issue is that you skipped a version number, in which case you should change the version number).

If you do not want to fix the AutoMerge issues, please post a comment explaining why you would like this pull request to be manually merged. Then, send a message to the `#pkg-registration` channel in the [public Julia Slack](https://julialang.org/slack/) to ask for help.

## To pause or stop registration

If you want to prevent this pull request from being auto-merged, simply leave a comment. If you want to post a comment without blocking auto-merging, you must include the text `[noblock]` in your comment. You can edit blocking comments, adding `[noblock]` to them in order to unblock auto-merging.

**Comment by DilumAluthge** [comment]
Could we also number the top-level section headers? Might make it a little easier to visually navigate.

**Comment by DilumAluthge** [comment]
Your example reformatting above seems like an improvement to me!
