### ISSUE TITLE
Decrease verbosity

### ISSUE THREAD

**Issue by fredrikekre** [JuliaRegistries/RegistryCI.jl#8]
In the web interface you can leave a comment with the approve, does the API allow that? Would send a single notification instead of both https://github.com/JuliaRegistries/General/pull/4422#issuecomment-542615772 and the approve.

**Comment by fredrikekre** [comment]
Also; maybe this comment is superfluous: https://github.com/JuliaRegistries/General/pull/4422#issuecomment-542628805 ?

**Comment by DilumAluthge** [comment]
> Also; maybe this comment is superfluous: [JuliaRegistries/General#4422 (comment)](https://github.com/JuliaRegistries/General/pull/4422#issuecomment-542628805) ?

I agree. Actually I think that I put that comment in as a debugging purpose, and never ended up taking it out. I’ll take that comment out.

**Comment by DilumAluthge** [comment]
> In the web interface you can leave a comment with the approve, does the API allow that? Would send a single notification instead of both [JuliaRegistries/General#4422 (comment)](https://github.com/JuliaRegistries/General/pull/4422#issuecomment-542615772) and the approve.

This should be doable. Currently I do actually use the comment body of the approval to store the SHA that was approved. You can’t see it, because I hide it in an HTML comment. So it should be easy to just use the comment body of the approval for everything. I’ll just need to make sure that it doesn’t break anything.

**Comment by fredrikekre** [comment]
> This should be doable. Currently I do actually use the comment body of the approval to store the SHA that was approved. You can’t see it, because I hide it in an HTML comment.

Turns out that on the mobile page you can see the comment but it is displayed as empty (empty white block) whereas on GH it is not shown at all.

**Comment by DilumAluthge** [comment]
Huh, interesting.

At any rate, I think the best approach will be to put the text of the “congratulations you met the guidelines” message inside the approval body. And then I’ll still have the hidden (commented out) message at the end, but it won’t be visible.
