### ISSUE TITLE
Trying to merge too fast?

### ISSUE THREAD

**Issue by fredrikekre** [JuliaRegistries/RegistryCI.jl#85]
Cleaned up logs from https://github.com/JuliaRegistries/General/runs/281762322#step:5:0:
```
[ Info: Now examining pull request 4890
[ Info: Pull request: 4890. Type: NewVersion. Decision: merge now.
[ Info: Attempting to squash-merge pull request #4890
┌ Debug: sha = 891fd7de6173ddbba186570f63d67d08f4da4f8d
└ @ RegistryCI.AutoMerge ~/.julia/packages/RegistryCI/x6ZH8/src/AutoMerge/github.jl:160

[ Info: Now examining pull request 4888
[ Info: Pull request: 4888. Type: NewVersion. Decision: merge now.
[ Info: Attempting to squash-merge pull request #4888
┌ Debug: sha = 9dedc9b57e660f82f2c5f3f7477be3712b36c14f
└ @ RegistryCI.AutoMerge ~/.julia/packages/RegistryCI/x6ZH8/src/AutoMerge/github.jl:160
Error found in GitHub reponse:
   Status Code: 405
   Message: Base branch was modified. Review and try the merge again.
   Docs URL: https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button
   Errors: 
Stacktrace:
 [1] error(::String, ::String, ::String, ::String, ::String) at ./error.jl:42
 [2] handle_response_error(::HTTP.Messages.Response) at /home/runner/.julia/packages/GitHub/oQdYa/src/utils/requests.jl:159

[...]

[ Info: Now examining pull request 4814
[ Info: Pull request: 4814. Type: NewVersion. Decision: merge now.
[ Info: Attempting to squash-merge pull request #4814
┌ Debug: sha = 9e6239ac91bca4e0d165b7405d90f5460e6c3236
└ @ RegistryCI.AutoMerge ~/.julia/packages/RegistryCI/x6ZH8/src/AutoMerge/github.jl:160
```
So it looks like the second merge try was too fast after the first one, but then after examining some more PRs (`[...]`) it worked. It is a bit weird that it works on Travis, but maybe everything is a bit slower there and we were lucky?

**Comment by fredrikekre** [comment]
Also, looks like we don't even retry for `merge!` given that we have a try-catch inside:
https://github.com/JuliaRegistries/RegistryCI.jl/blob/12a7484a7094250b71e20063ab0e625cddb2fc86/src/AutoMerge/github.jl#L161-L171

So we never retry:
https://github.com/JuliaRegistries/RegistryCI.jl/blob/12a7484a7094250b71e20063ab0e625cddb2fc86/src/AutoMerge/cron.jl#L183

**Comment by fredrikekre** [comment]
We can use a `first_delay=10` or something.

**Comment by DilumAluthge** [comment]
Yeah, I guess it worked on Travis because things were slow on Travis.

Every time the base branch (i.e. the master branch) is updated, GitHub needs to recheck the merge ability of a poor request. This only takes a few seconds. But if you try to merge before Github has verified that a pull request is mergeable, you get this error.

Because the merge API endpoint triggers the abuse limit, Instead of just re-trying to merge, I think the correct solution to this is to check if the mergeability computation has completed before we try to merge.

```
function wait_pr_compute_mergeability(repo::GitHub.Repo, pr::GitHub.PullRequest; auth::GitHub.Authorization)
    sleep(5)
    pr = GitHub.pull_request(repo, pr.number; auth = auth)
    num_tries = 0
    max_tries = 10
    while !(pr.mergeable isa Bool) && num_tries <= max_tries
        num_tries = num_tries + 1
        sleep(5)
        pr = GitHub.pull_request(repo, pr.number; auth = auth)
    end
    return pr
end
```

So we just do this right before merging:
```
wait_pr_compute_mergeability(registry_repo, pr; auth = auth)```

**Comment by DilumAluthge** [comment]
@fredrikekre I just noticed your last comment. Yeah your suggestion is much simpler and better than the complicated thing I suggested. Let’s just do that and add a delay.

**Comment by fredrikekre** [comment]
Ideally we would actually check why it failed though. If the problem is that there are conflicts for example, then there is no point of retrying. But maybe doesn't matter.

**Comment by DilumAluthge** [comment]
That’s doable. We would have to parse the error message, extract the status code in the message, and do some pattern matching.

**Comment by DilumAluthge** [comment]
Although, if you want to check if there are merge conflicts, it’s much easier to do. Just get the PR from the API, and check the `mergeable` field. Value of true means no merge conflicts, value of false means merge conflict.
